-- CreateEnum
CREATE TYPE "STATUS_REQUEST" AS ENUM ('PENDING', 'DONE', 'ENTERED', 'FAILED');

-- CreateEnum
CREATE TYPE "STATUS_SERVICES" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "SERVICES" AS ENUM ('CITIZEN_ID_CARD_INFO', 'CITIZEN_BIRTH_INFO', 'CITIZEN_ADDRESS_INFO', 'CITIZEN_MARRIAGE_INFO', 'CITIZEN_MARRIAGE_DIVORCE_INFO', 'AUTHORIZE_CITIZEN', 'CITIZEN_INFO', 'CHECK_CITIZEN_REGNUM', 'CITIZEN_NO_MARRIEGE_INFO', 'PROPERTY_INFO', 'PROPERTY_LIST', 'LEGAL_ENTITY_INFO_WITH_REGNUM', 'VEHICLE_INFO_OLD', 'VEHICLE_OWNER_HISTORY_LIST', 'VEHICLE_PENALTY_LIST', 'CITIZEN_VEHICLE_LIST', 'DRIVER_LICENSE_INFO', 'SALARY_INCOME', 'CITIZEN_PENSION_INQUIRY', 'TAX_PAYER_INFO', 'VEHICLE_PAID_TAX_HISTORY', 'VEHICLE_TAX_PAYABLE_INFO', 'VEHICLE_INFO');

-- CreateTable
CREATE TABLE "request" (
    "id" SERIAL NOT NULL,
    "unique" VARCHAR(255) NOT NULL,
    "callback" VARCHAR(300) NOT NULL,
    "state" TEXT NOT NULL,
    "services" JSONB[],
    "status" "STATUS_REQUEST" NOT NULL,
    "scope" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "request_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "services" (
    "id" SERIAL NOT NULL,
    "key" TEXT NOT NULL,
    "code" "SERVICES" NOT NULL,
    "desc" TEXT NOT NULL,
    "wsdl" TEXT,
    "status" "STATUS_SERVICES" NOT NULL DEFAULT E'ACTIVE',
    "params" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "request_state_key" ON "request"("state");

-- CreateIndex
CREATE UNIQUE INDEX "services_key_key" ON "services"("key");

-- CreateIndex
CREATE UNIQUE INDEX "services_code_key" ON "services"("code");
